# Copyright (c) 2022-2025, The Isaac Lab Project Developers (https://github.com/isaac-sim/IsaacLab/blob/main/CONTRIBUTORS.md).
# All rights reserved.
#
# SPDX-License-Identifier: BSD-3-Clause

# Reference: https://github.com/DLR-RM/rl-baselines3-zoo/blob/master/hyperparams/sac.yml
seed: 42

# Algorithm class to use
algorithm: "SAC"

# Total timesteps for training
n_timesteps: 1500000000
policy: 'MlpPolicy'
learning_rate: !!float 3e-4
buffer_size: 1000000
learning_starts: 10000
batch_size: 256
tau: 0.005
gamma: 0.99
train_freq: 1
gradient_steps: 1
ent_coef: 'auto'  # automatically adjust entropy coefficient
target_entropy: 'auto'  # auto: -dim(action_space)
use_sde: False
policy_kwargs:
  net_arch: [256, 256]
  activation_fn: 'nn.ReLU'
device: "cuda:0"
